# Generated by Django 3.0 on 2020-11-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0004_remove_cusbooking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='emg_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='emg_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='route',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cusbooking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cusbooking',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='cusbooking',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='cusbooking',
            name='emg_name',
        ),
        migrations.RemoveField(
            model_name='cusbooking',
            name='emg_phone',
        ),
        migrations.RemoveField(
            model_name='cusbooking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cusbooking',
            name='status',
        ),
    ]
