# Generated by Django 3.0 on 2020-11-30 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0005_auto_20201130_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='agent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='emgergency_Contact_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='emgergency_Contact_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theApp.Routes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Active Booking', 'Active Booking'), ('Used Booking', 'Used Booking')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cusbooking',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cusbooking',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cusbooking',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cusbooking',
            name='emgergency_Contact_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cusbooking',
            name='emgergency_Contact_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cusbooking',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cusbooking',
            name='status',
            field=models.CharField(choices=[('Active Booking', 'Active Booking'), ('Used Booking', 'Used Booking')], max_length=200, null=True),
        ),
    ]
