# Generated by Django 3.0 on 2020-11-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0007_cusbooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cusbooking',
            name='user',
        ),
    ]
